# Generated by Django 5.0.1 on 2024-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_item_created_item_description_item_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
