# Generated by Django 5.0.1 on 2024-10-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title_is',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
