# Generated by Django 5.0.1 on 2024-10-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_about_title_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_filde',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
